name: Tool Filter
favicon: null
layout_spectrum: 0.25209
typography_spectrum: 0.50584
title: Comparative Search and Review Tool For Machinists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#4a5c66'
    - '#1f2c3d'
    - '#71838d'
    - '#9eabbc'
  brandStrength: 0.5
  lightness: 0.15001529082655907
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
