name: Tool Filter
favicon: null
layout_spectrum: 0.027518206275999546
typography_spectrum: 0.06673846393823624
title: Comparative Search and Review Tool For Machinists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08969576214440167
  lightness: 0.15001529082655907
  saturation: 0.6897490008268505
  rhythmicContrast: 0.10831136675551534
purpose: []
