name: Tool Filter
favicon: null
layout_spectrum: 0.25209
typography_spectrum: 0.50584
title: Tool Filter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#4a5c66'
    - '#1f2c3d'
    - '#71838d'
    - '#9eabbc'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
